/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nuri
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cbmArchivoSalir = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cbmMaterias = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        cbmAlumnos = new javax.swing.JCheckBoxMenuItem();
        jMenu4 = new javax.swing.JMenu();
        cbmInscripcion = new javax.swing.JCheckBoxMenuItem();
        jMenu5 = new javax.swing.JMenu();
        cbmNotas = new javax.swing.JCheckBoxMenuItem();
        jMenu6 = new javax.swing.JMenu();
        cbmConsultaNotas = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        cbmArchivoSalir.setSelected(true);
        cbmArchivoSalir.setText("Salir");
        cbmArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmArchivoSalirActionPerformed(evt);
            }
        });
        jMenu1.add(cbmArchivoSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Materias");

        cbmMaterias.setSelected(true);
        cbmMaterias.setText("Formulario Materias");
        jMenu2.add(cbmMaterias);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Alumnos");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        cbmAlumnos.setSelected(true);
        cbmAlumnos.setText("Formulario Alumnos");
        cbmAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmAlumnosActionPerformed(evt);
            }
        });
        jMenu3.add(cbmAlumnos);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Inscripcion");

        cbmInscripcion.setSelected(true);
        cbmInscripcion.setText("Manejo de Inscripcion");
        jMenu4.add(cbmInscripcion);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Carga de Notas");

        cbmNotas.setSelected(true);
        cbmNotas.setText("Manipulacion de Notas");
        jMenu5.add(cbmNotas);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Consultas");

        cbmConsultaNotas.setSelected(true);
        cbmConsultaNotas.setText("Listado Alumnos por Materia");
        jMenu6.add(cbmConsultaNotas);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbmArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmArchivoSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmArchivoSalirActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu3ActionPerformed

    private void cbmAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmAlumnosActionPerformed
        // TODO add your handling code here:
        FormularioAlumnos ventana = new FormularioAlumnos();
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_cbmAlumnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JCheckBoxMenuItem cbmAlumnos;
    private javax.swing.JCheckBoxMenuItem cbmArchivoSalir;
    private javax.swing.JCheckBoxMenuItem cbmConsultaNotas;
    private javax.swing.JCheckBoxMenuItem cbmInscripcion;
    private javax.swing.JCheckBoxMenuItem cbmMaterias;
    private javax.swing.JCheckBoxMenuItem cbmNotas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
